# Gunakan image Node.js yang stabil
FROM node:16

# Tentukan working directory
WORKDIR /ml-api/src

# Salin package.json dan package-lock.json untuk menginstal dependencies
COPY package*.json ./

# Instal dependencies
RUN npm install

# Salin seluruh aplikasi
COPY . .

# Ekspos port yang akan digunakan
EXPOSE 8080

# Jalankan aplikasi
CMD ["npm", "start"]
